nodeLinker: node-modules

npmScopes:
  kausal:
    npmAlwaysAuth: true
    npmAuthIdent: ${PRIVATE_NPM_TOKEN}
    npmRegistryServer: "https://npm.kausal.tech"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
